const activityGroups = ['','Broadcasting and communication',
'Integrated administrative services activities for offices',
'Medical clinics',
'Education services',
'Airplanes Trading',
'Other metal industries',
'Educational Consulting Services',
'Equipment and Machinery industry',
'Equipment and engines manufacturing',
'Accounts',
'Accounting Activities',
'Training Institute',
'Chemicals trading',
'Chemical industry',
'Media',
'Manufacturing of chemicals',
'Consultation and project management',
'Consultancy -D- management, information and marketing',
'Agricultural',
'publicity and announcement',
'Advertising',
'Media & Marketing Services',
'Ready made garments qroup',
'Regional liaison office',
'Ship services',
'Legal services',
'Investment',
'Wholesale of machinery, equipment and supplies',
'Consulting - agriculture and soil',
'Consultancy -A- Agriculture and Soil',
'Air Shipment and Transportation Services',
'Transport, shipping and storage',
'Electronic devices industry',
'refrigeration or air conditioning appliances',
'Home appliance industry',
'Mechanical & engineering equipment trading',
'Waste trading',
'Light aircraft manufacturing and maintenance',
'Manufacture of air and spacecraft and related machinery',
'Manufacturing cars, spare parts, vehicles and bicycles',
'Travel agency Activities',
'Consulting - Engineering and Architecture',
'safety and security equipment',
'Personal requisities manufacturing',
'Building contracting - not specified',
'Professional 2',
'Alternative energy and space',
'Research and Development',
'Other metal indusries',
'Casting of steel and iron',
'Appliances and machinery manufacturing',
'General',
'Fodder and fertilizers manufacturing',
'Veterinary clinic',
'Fodders & animal food trading',
'Meat and poultry industry',
'Meat processing',
'Breeding of livestock, poultry and bees',
'Electronics group',
'Manufacturing of garments and rugs',
'Other engineering services',
'Block and building stones industry',
'Services',
'Lounges and galleries',
'Creative, arts and entertainment activities',
'Blacksmith and Turning',
'Food Industry',
'E-Gaming Core',
'Industrial',
'Manual workshops',
'Handicraft workshops',
'NATURAL STONE AND MARBLE',
'Pharmaceutical industry',
'BUILDING MATERIALS INDUSTRY',
'Manufacture of petroleum products',
'Industrial 1',
'Organization of conventions and trade shows',
'Plastic industries',
'Visual & Audio Recording',
'Consulting - Management and Information',
'Manufacture of motor vehicles, motorcycles & its spare parts',
'Auto spare parts trading',
'Pipes and wires manufacturing',
'storing Services',
'Combing and upholstery',
'Manufacture of mats and rugs',
'Sport Club',
'Transportation consulting',
'Textile industry and its products',
'Manufacturing of paper and paper products',
'Medicines trading',
'manufacture of engines and Vehicles',
'Food industries',
'Foodstuff trading',
'Restaurants and coffee shops',
'Manufacturing of wood, wood products and Furniture',
'Furnitures trading',
'Banking services',
'Financial Consulting',
'Head Offices',
'Cotton & metal nets & ropes manufacturing',
'Metal construction industry',
'Industrial 2',
'Gold industry and cutting gemstones',
'Manufacture of basic precious and other non-ferrous metals',
'Manufacture of wood and its products and furniture',
'Waste collection and treatment',
'Personal supplies industry',
'outlet group',
'manufacture of machinery for the manufacture of foodstuffs',
'Sports equipment trading',
'Halls and exibition',
'Home appliances trading',
'Poultry Trading',
'Bread manufacturing',
'Mattresses and mattresses industry',
'Metal containers & boxes manufacturing',
'IT Services',
'Ship building and repairing',
'steel tool manufacturing',
'Building materials trading',
'Publishing',
'Publishing and printing services',
'Books, Newspapers & Publications Trading',
'Agricultural equipment industry',
'pharmacy',
'Paper and paper products',
'Higher Education Provider',
'Marketing services',
'Baking industry',
'Broadcast Support Services',
'Plastic household items industry',
'Metal home appliances manufacturing',
'Demolition and site preparation',
'Building contracting (third degree)',
'Structural steel manufacturing',
'Manufacture of ovens, stoves and torches',
'Trading in motor vehicles and motorcysles',
'Vehicle spare parts trade',
'Trade cars and bicycles',
'Trade in used cars and bicycles',
'Others fields',
'Real estate',
'Event Management Services',
'Printing offices',
'Business Support Service',
'Separate trading activities',
'Manufacture of non-metallic mineral products',
'water manufacturing and bottling',
'Education',
'Metals & its products trading',
'Blacksmith and aluminum',
'laundry',
'Carpet & mat manufacturing',
'Cars Care',
'Tire repair and oil replacement',
'Vehicles repair',
'Car Rental',
'General Trading',
'Production (Film, TV & Radio)',
'Smelting and rolling iron and minerals',
'Metal industries',
'Pipes and wires industry',
'Foodstuff supply',
'Paint and insulators industry',
'Light aircraft manufacturing & maintenance',
'Manufacture of lighting equipment',
'Collection and treatment of waste',
'Metal containers, boxes and tanks industry',
'Grinding and packing food',
'Foodstuff mills and packaging',
'Manufacture of nets and ropes',
'Lighting equipment manufacturing1',
'Wholesale of household goods',
'Crop planting',
'Separate industrial activities',
'Technical testing and analysis',
'Petroleum storage',
'tobacco trade and smoking supplies',
'Wholesale of food, beverages and tobacco',
'tobacco products manufacturing',
'Consultancy -B- Engineering',
'building Maintenance',
'Data processing, hosting and related activities',
'Fuel and petroleum products trading',
'Floor mills',
'Wholesale on a fee or contract basis',
'SHIPPING SERVICES',
'Renting and leasing of machinery, equipment and tangible goods',
'Computer programming, consultancy and related activities',
'Extraction of petroleum and other materials',
'Shipbuilding and repair',
'Consultations and studies',
'Veterinary clinics',
'Banking, Finance and Credit Group',
'Manufacture of eyeglasses',
'General Media',
'Cooperation Societies',
'Professional Services',
'Manufacture of household appliances',
'finance consultants',
'Textiles & products manufacturing',
'Design, Media & Architecture',
'Oil products industry',
'Military equipments industry',
'Management of facilities',
'Consultancy –Technical',
'Painting and Decoration',
'Information service activities',
'Data Entry & Admin',
'Business support Services',
'Printing and publishing services',
'Management consultancy',
'Car registration and travel services',
'Digital Media',
'Manufacture of Plastic Products',
'Technical & proffesional workshops',
'Other Rental Services',
'Cleaning services',
'Destruction and archiving of documents',
'Consultancy -C- Petrol and Water',
'Consulting - oil and water',
'Water desalination plants',
'Bags and shoes industry',
'Battery industry',
'Tourism Activites',
'Stationary and books trading',
'electrical and electronic devices repairing',
'Elecricals trading',
'Power generation and Distribution',
'Mechanical & Engineering Equipment Trading',
'mobile phones Tading',
'Tobacco and smoking accessories trading',
'Design and programming services',
'Packing services',
'Electronic Nicotine Products',
'Glass and glass products industry',
'Professional 1',
'Entertainment equipment and supplies trading',
'E-Commerce',
'E-sports',
'Real Estate',
'Laboratories',
'Building contracting (second class)',
'Executive Search',
'Jewelry trading',
'Exporting',
'Other Trading Activities',
'Agricultural equipment and tools',
'BOTIQUE AND CAFE',
'Specialized design activities',
'Gents tailoring and design',
'Glass and ceramic ware industry',
'Glass industries',
'Non-specialized wholesale trade',
'Music and Entertainment',
'studio - trade license',
'Technical training institutes',
'Food trade',
'Fish canning & freezing',
'Manufacture of vegetable and animal oils and fats',
'Fish trade',
'Fishing cages & net manufacturing',
'Ship and boat trade',
'Cotton tease and upholstery',
'Manufacture of tyres and rubber products',
'Flowers and plants',
'Sports clubs',
'Food supply',
'Perfumery',
'Special security activities',
'Fish trading',
'vegetables and fruits',
'Oil and natural gas services',
'Furniture trading',
'E-Gaming',
'Waste and Garbage trade',
'Domestic gas distribution',
'Hospitals and convalescents',
'Packaging',
'Glass & chinaware manufacturing',
'Manufacture of gold and precious stones cutting',
'Casting of non-ferrous metals',
'Grocery',
'Consumer Stores Group',
'Manufacturing of bags, shoes and leather products',
'Metal tools industry',
'Health Care',
'heavy machinery and equipment trading',
'Equipment repair',
'Chemical trade',
'leather trading',
'religious organizations',
'Tourist activities',
'HR Consulting',
'Importing',
'household electrical appliances repairing',
'Factories and workshop equipment',
'Software deployment',
'Commercial',
'Insurance',
'Insurance services',
'Leasing of intellectual property and similar products, except copyrighted works',
'Service',
'Wireless telecommunications activities',
'Sales & Marketing',
'Computer Devices Trading',
'Broadcasting (TV & Radio)',
'Goldsmith & gold repairing',
'Jewellery trading',
"Goldsmith's jewelery, precious stones and more",
'Building Contracting (Fourth degree)',
'Steel workshop',
'manufacture of textile machines',
'Advocacy and legal advice',
'translation group',
'Translation',
'Bricks and building stones',
'Shipment and Transportation Services',
'Manufacture of refined petroleum products',
'Metal Industries',
'Aluminium and Glass',
'Alcoholic beverage industry',
'Manufacture of military boats',
'Manufacture of tires and rubber products',
'Industrial Engineering products',
'Animal Raising',
'Marine Shipment and Transportation Services',
'Meat trading',
'Coating, insulations, seals & protection materials manufactu',
'medical equipment trading',
'Manufacture of medicines',
"Men's salons and beauty centers",
'Materials recovery',
'Metal household appliances industry',
'Super Market',
'Activities auxiliary to financial service activities, except insurance and pension funding',
'Family Office Management',
'Business Information',
'Non-Academic Services',
'Information Provision Services',
'Agricultural equipment',
'nursery',
'Repair of fabricated metal products, machinery and equipment',
'Web Portals',
'Optical industry',
'Holding Companies',
'Bags, backaging materials & paper trading',
'Paper home appliances manufacturing',
'Separate professional activities',
'Parties organization',
'Business support service',
'Stationary manufacturing',
'Research and experimental development on natural sciences and engineering',
'Photography studio',
'Recycling of Non-Metal Waste and Scrap',
'Electronics and electrical appliances',
'JEWELLERY Trading',
'Manufacture of Jewellery and related articles',
'imaging equipment',
'Management training institutes',
'Recruitment Services',
'Materials Recovery',
'office tools trading',
'METAL INDUSTRIES',
'Restaurants and cafeteria',
'Facility management',
'Roastry',
'Non-metallic mineral products Manufacturing',
'lockers rental and trading',
'Crushers and Quarrying',
'Commercial 4',
'Other professional, scientific and technical activities not elsewhere classified',
'Commercial mediation',
'Family Offices',
'Medical eye glasses trading & eyes testing services',
'Sports equipment',
'Sports Services',
'Engineering & Science',
'Cutting, shaping and finishing of stone',
'Supermarket',
'Broadcasting and communications',
'Professional1',
'tents & tarpaulin trading',
'Pets trading',
'Leisure and recreation activities',
'Electrical trading',
'Commercial 2',
'Labor supply and employment',
'Used auto spare parts trading',
'Used heavy equipment trading',
'Used electronics & furniture trading',
'Sale, maintenance and repair of motorcycles and related parts and accessories',
'Time sharing',
'Veterinary equipment trading',
'Veterinary equipment trade',
'Applied studies',
'Sewage',
'House Machines Trading',
'building materials trading',
'Trade in cosmetics and child care',
'Banking equipment trading',
'sport equipments trading',
'livestock and horses Trading',
'Trading minerals and products',
'Cleaning Equipment Trading',
'Measurement and control equipment',
'Garments Trading',
'Fuel trade and oil derivatives',
'Roasting',
'Cards issuing services',
'haberdashery and tailoring tools',
'Electromechanical equipment trade',
'Library',
'Wholesale of metals and metal ores',
'Machinery equipment rental and trading',
'FINE ART',
'Commercial 3',
'kitchens trading',
'Trains trade',
'Motor and bike education institutes',
'raw hides and animal remains Trading',
'Animal skin trading']

module.exports = activityGroups;